# Generated by Django 5.2.8 on 2025-11-26 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("paid", "Paid")],
                        default="pending",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("payment", "Payment"), ("fine", "Fine")],
                        default=None,
                        null=True,
                    ),
                ),
                ("session_url", models.URLField(blank=True, max_length=255, null=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("money_to_pay", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="borrow.borrow"
                    ),
                ),
            ],
        ),
    ]
