# Generated by Django 5.2.8 on 2025-12-03 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrow", "0001_initial"),
        ("payments", "0002_alter_payment_borrowing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="borrowing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="borrow.borrow",
            ),
        ),
    ]
