# Generated by Django 5.2.8 on 2025-12-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_borrowing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("pending", "Pending"), ("paid", "Paid")],
                default=None,
                null=True,
            ),
        ),
    ]
