# Generated by Django 5.2.8 on 2025-12-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("paid", "Paid")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("payment", "Payment"), ("fine", "Fine")],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
