# Generated by Django 5.2.8 on 2025-11-11 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "cover",
                    models.CharField(
                        choices=[("hard", "Hard"), ("soft", "Soft")], max_length=255
                    ),
                ),
                (
                    "inventory",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("daily_fee", models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("title", "author", "cover"),
                        name="unique_title_author_cover",
                    )
                ],
            },
        ),
    ]
